M48
; DRILL file {KiCad 9.0.1} date 2025-05-06T22:51:10-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-06T22:51:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X107.0Y-75.075
X107.0Y-79.925
T2
X103.97Y-74.775
X103.97Y-80.225
M30
